# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'JiaXinDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JiaXinDemo
  
  pod 'JiaxinIM',:path=>'../'

  target 'JiaXinDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JiaXinDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
